version: 1.0.1.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: 1.0.1-beta{build}
install:
- cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe
before_build:
- cmd: nuget restore -Verbosity quiet
build:
  project: dbsafe.sln
  verbosity: minimal
test_script:
- cmd: dotnet test "DbSafeTests\DbSafeTests.csproj"
artifacts:
- path: '**\bin\Release\*.nupkg'
  name: NuGet