version: 1.0.0-beta-{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
build:
  project: dbsafe.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
before_build:
  nuget help
  nuget restore
after_test:
  dotnet test
