version: $(build_version).{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  api_key:
    secure: TFDaKD4TQc7hWomFzKAW6CDYnYqboEgFZ6a8d5+1T3J+RL647PsgqrlIXLHWjH19
  build_version: 1.0.19
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'

  # use for release
  # version: $(build_version)
  # package_version: $(build_version)

  # use for beta
  version: $(build_version)-beta{build}
  package_version: $(build_version)-beta{build}
install:
- cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe
nuget:
  account_feed: true
before_build:
- cmd: >-
    nuget restore -Verbosity quiet

    powershell.exe -file UpdateBuildVersion.ps1 -assemblyVersion %APPVEYOR_BUILD_VERSION%
build:
  project: dbsafe.sln
  verbosity: minimal
test_script:
- cmd: dotnet test "DbSafeTests\DbSafeTests.csproj"
artifacts:
- path: '**\bin\Release\*.nupkg'
  name: NuGet
deploy_script:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe  
  - powershell.exe -file DeployNuGetPackages.ps1
