version: 1.0.0-beta-{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
install:
  - cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe
build:
  project: dbsafe.sln
  publish_nuget: false
  publish_nuget_symbols: true
  verbosity: minimal
before_build:
  nuget help

  nuget restore
after_test:
  dotnet test
