version: 1.0.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: 1.0.0-beta{build}
  package_version: 1.0.0-beta{build}
install:
- cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe
before_build:
- cmd: >-
    nuget restore -Verbosity quiet

    powershell.exe -file UpdateBuildVersion.ps1 -assemblyVersion %APPVEYOR_BUILD_VERSION%
build:
  project: dbsafe.sln
  verbosity: minimal
test_script:
- cmd: dotnet test "DbSafeTests\DbSafeTests.csproj"
artifacts:
- path: '**\bin\Release\*.nupkg'
  name: NuGet