variables:
  - name: _version
    value: $(VersionMajor).$(VersionMinor).$(VersionPatch).$(Build.BuildId)
  - name: _packageVersion
    value: $(_version)$(PrereleaseLabel)

trigger:
- main

pool: 
  vmImage: ubuntu-latest

stages:
- stage: CI
  displayName: Build and test
  jobs:
    - job: BuildAndTest
      displayName: Build and test
      steps:
      # - script: sqllocaldb info
      #   displayName: Print localdb info
      
      # - script: sqlcmd
      #   displayName: Check if build server has sqlcmd

      # - script: dotnet --version
      #   displayName: Print dotnet version
      - script: dotnet build /warnaserror --configuration Release -p:Version=$(_version) -p:PackageVersion=$(_packageVersion)
        displayName: Build solution
      # - script: ls
      #   displayName: Print current location
      - script: dotnet test ./DbSafeTests/
        displayName: Tests DbSafe project

      - script: git clone https://github.com/dbsafe/dbsafe-pg-db
        displayName: Checkout test database
      - script: docker-compose -f ./dbsafe-pg-db/docker-compose.yml up --build -d
        displayName: Start container with PostgreSql database
      - script: docker ps
        displayName: Print Docker containers
        
      - script: dotnet test ./PgDbSafeTests/
        displayName: Tests PgDbSafe project        
        
  