trigger:
- main

pool: 
  vmImage: ubuntu-latest

stages:
- stage: CI
  displayName: Build and test
  jobs:
    - job: BuildAndTest
      displayName: Build and test
      steps:
      - script: dotnet build
        displayName: Build solution
      - script: dotnet test .\DbSafeTests\
        displayName: Tests DbSafe project
  