name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(VersionMajor).$(VersionMinor).$(VersionPatch).$(Build.BuildId)$(PrereleaseLabel)

variables:
  - name: _version
    value: $(VersionMajor).$(VersionMinor).$(VersionPatch).$(Build.BuildId)
  - name: _packageVersion
    value: $(_version)$(PrereleaseLabel)
  - name: _publishNugetPackages
    value: $[or(eq(variables['PrereleaseLabel'], ''), eq(variables['PrereleaseLabel'], '-beta'))]

trigger:
- master

pool: 
  vmImage: ubuntu-latest

steps:
- script: echo $(Build.ArtifactStagingDirectory)
  displayName: Print Build.ArtifactStagingDirectory

- script: dotnet build /warnaserror --configuration Release -p:Version=$(_version) -p:PackageVersion=$(_packageVersion) -p:PackageOutputPath=$(Build.ArtifactStagingDirectory)
  displayName: Build solution 

- script: tree $(Build.ArtifactStagingDirectory)
  displayName: Print files in Print Build.ArtifactStagingDirectory

- task: DotNetCoreCLI@2
  displayName: Execute Unit Tests
  inputs:
    command: 'test'
    projects: './DbSafeTests/DbSafeTests.csproj'

- script: git clone https://github.com/dbsafe/dbsafe-pg-db
  displayName: Checkout PostgreSql test database
- script: docker compose -f ./dbsafe-pg-db/docker-compose.yml up --build -d
  displayName: Start container with PostgreSql database
- script: docker ps
  displayName: Print Docker containers

- script: git clone https://github.com/dbsafe/dbsafe-sql-db
  displayName: Checkout MS-SQL Server test database
- script: docker compose -f ./dbsafe-sql-db/docker-compose.yml up --build -d
  displayName: Start container with MS-SQL Server
- script: docker ps
  displayName: Print Docker containers

- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: ./dbsafe-pg-db/wait-for-db.ps1
    arguments: >
      -ContainerName demo-pg-db 
      -MaxNumberOfTries 120
  displayName: Wait for PostgreSql database

- task: DotNetCoreCLI@2
  displayName: Tests PgDbSafe project
  inputs:
    command: 'test'
    projects: './PgDbSafeTests/PgDbSafeTests.csproj'

- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: ./dbsafe-sql-db/wait-for-db.ps1
    arguments: >
      -ContainerName demo-sql-db 
      -MaxNumberOfTries 120
  displayName: Wait for MS-SQL Server database

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: Install-Module SQLServer -Force -AllowClobber
  displayName: Installing PS Module SqlServer

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: Invoke-Sqlcmd -InputFile ./dbsafe-sql-db/ProductDatabase.sql -ConnectionString "Data Source=localhost;Initial Catalog=master;Integrated Security=False;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True"
  displayName: Deploy MS-SQL database using script

- task: DotNetCoreCLI@2
  displayName: Tests SqlDbSafe project
  inputs:
    command: 'test'
    projects: './SqlDbSafeTests/SqlDbSafeTests.csproj'

- task: PublishBuildArtifacts@1
  condition: and(succeeded(), eq(variables._publishNugetPackages, 'true'))
  displayName: 'Publish Artifact'
  inputs:
    ArtifactName: '$(Build.BuildNumber)'

- script: dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg --source https://api.nuget.org/v3/index.json --api-key $(nuget-api-key)
  condition: and(succeeded(), eq(variables._publishNugetPackages, 'true'))
  displayName: 'Publish NuGet Packages'
