trigger:
- main

pool: 
  vmImage: ubuntu-latest

stages:
- stage: CI
  displayName: Build and test
  jobs:
    - job: BuildAndTest
      displayName: Build and test
      steps:
      - script: dotnet --version
        displayName: Print dotnet version
      - script: dotnet build --configuration Release
        displayName: Build solution
      - script: ls
        displayName: Print current location
      - script: dotnet test .\DbSafeTests\
        displayName: Tests DbSafe project
  