version: '3.1'

services:

  db:
    restart: always
    build:
      context: ./Docker
      dockerfile: Dockerfile
    ports:
      - 5432:5432    

# adminer is an image for Adminer (a database management tool)
# is is not needed for the tests to execute.

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080